# Generated by Django 4.2.2 on 2023-12-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cousins',
            name='photo',
            field=models.FileField(default='eee', upload_to=''),
            preserve_default=False,
        ),
    ]
