# Generated by Django 5.0.3 on 2024-03-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemoapp', '0003_registration_delete_cousins'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_teacherinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_pic', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('subject1', models.CharField(max_length=100)),
                ('subject2', models.CharField(max_length=100)),
                ('subject3', models.CharField(max_length=100)),
                ('subject4', models.CharField(max_length=100)),
                ('subject5', models.CharField(max_length=100)),
            ],
        ),
    ]
