# Generated by Django 5.0.3 on 2024-03-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydemoapp', '0005_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='files',
        ),
    ]
